//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetailingCenter.Model.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int ClientId { get; set; }
        public int ServiceId { get; set; }
        public int CarId { get; set; }
        public int CarColor { get; set; }
        public System.DateTime DateOfService { get; set; }
    
        public virtual CarModel CarModel { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Service Service { get; set; }
        public virtual Client Client { get; set; }
    }
}
